-- Generated by nwg-displays on 2026-05-21 at 00:48:59. Do not edit manually.

hl.monitor({
	output = "DP-1",
	mode = "3840x2160@120.00",
	position = "0x0",
	scale = 1.33,
})
hl.monitor({
	output = "DP-2",
	mode = "2560x1440@179.84",
	position = "2880x360",
	scale = 1.07,
	bitdepth = 10,
})